name: R script check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: install dependencies
      run: |
        Rscript -e 'install.packages(c("data.table", "optparse", "remotes"), repos="https://cran.rstudio.com")' 
        Rscript -e 'remotes::install_github("ebi-gene-expression-group/workflowscriptscommon", ref="develop")'
    - name: run test
      run: |
        set -e
        out_test1=$(pwd)/test1
        Rscript bin/sdrfToNfConf.R --sdrf=tests/E-MTAB-4850.homo_sapiens.sdrf.txt --idf=tests/E-MTAB-4850.homo_sapiens.idf.txt --name=E-MTAB-4850 --verbose --out_conf $out_test1

    - name: check for errors
      run: Rscript -e 'stopifnot(identical(geterrmessage(), ""))'
